name: Build and tests
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        go-version:
          - 1.14.x
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Check out code
        uses: actions/checkout@v1

      - name: Build
        run: |
          go build

      - name: Run tests
        run: |
          export PATH=$HOME/bin:$PATH
          go test ./...
